version: '2'

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - localnet
  web:
    build: .
    command: ["./bin/wait-for-it.sh", "db:5432", "--", "bash", "./bin/run.sh"]
    volumes:
      - ./src/:/code
      - ./static/:/static
      - ./media/:/media
      - ./smedia/:/smedia
    environment:
      - ENV=docker
      - DEBUG
    depends_on:
      - "db"
    restart: always
    networks:
      - localnet
  proxy:
    image: nginx:latest
    ports:
      - "7005:8000"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - "web"
    environment:
      - VIRTUAL_HOST=lms.punch.vn
      - VIRTUAL_PORT=8000
    networks:
      - reverse-proxy
      - localnet

networks:
  localnet:
    driver: bridge
  reverse-proxy:
    external:
      name: reverse-proxy
